### ISSUE TITLE
Plus editor uses Arial instead of Helvetica on windows

### ISSUE THREAD

**Issue by Donnnno** [sn-extensions/plus-editor#61]
Hi,
I noticed that the Plus editor is actually using Arial, even when I specifically select Helvetica.

Here's a screenshot (look at that ugly arial R(!))

![image](https://user-images.githubusercontent.com/31142286/138256152-fe2e1bbf-15c3-4fc1-8e85-64d75a9a08f3.png)

**Comment by JaspalSuri** [comment]
Hi @Donnnno,

Since the font isn't included with the editor, it must be already installed on your desktop in order to render it. That's why it falls back on using Arial on Windows, since Helvetica is typically provided by macOS. 

Please let me know if it still doesn't work despite having Helvetica "installed" on your system.

**Comment by Donnnno** [comment]
Hi, thanks for the answer.
Turns out I had Helvetica Neue installed instead of the regular one.

![image](https://user-images.githubusercontent.com/31142286/138674469-06528298-281f-47d8-8c0e-8ffd92258eaa.png)

After installing the normal Helvetica, everything works again. 

![image](https://user-images.githubusercontent.com/31142286/138674646-538e13d5-7341-4ddf-87a1-112a281cb6f2.png)

**Comment by JaspalSuri** [comment]
That's great to hear; thank you for taking the time to let us know!
